# -*- coding: utf-8 -*-
"""2026LCS020_EXP_05

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E92mFjWc6FwjyZLYuzUCzWau8Td6nY71
"""

import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

df=pd.read_csv("/content/student_performance_dataset (4).csv")
print("First 5 rows of the dataset:")
print(df.head())

print("\nStastical Summary:")
print(df.describe())

numeric_cols=['Study_Hours_per_week', 'Attendance_Rate',
              'Past_Exam_Scores','Final_Exam_Score']

df.loc[0, 'Study_Hours_per_week'] = 120
df.loc[1, 'Attendance_Rate'] = 250
df.loc[2, 'Past_Exam_Scores'] = 20
df.loc[3, 'Final_Exam_Score'] = 200
print("\nIntrested a few artificial outliner values for demonstartion.")

print('\n-----IQR METHOD------')
for col in numeric_cols:
  Q1=df[col].quantile(0.25)
  Q3=df[col].quantile(0.75)
  IQR=Q3-Q1
  lower = Q1 - 1.5 * IQR
  upper = Q3 + 1.5 * IQR

  outliers = df[(df[col] < lower) | (df[col] > upper)]
  print(f"{col}: {len(outliers)} outerlier(s) found (limits: {lower:2f}) to {upper:2f})")

print("\n----Z.Score Method-----")
for col in numeric_cols:
  z_score = (df[col] - df[col].mean()) / df[col].std()
  outliers = df[z_score.abs() > 3]

  print(f"{col}: {len(outliers)} outlier(s) found (|z| > 3)")

print("\n------- Treatng Putliers (Capping using IQR limits)----")
df_treated = df.copy()
for col in numeric_cols:
  Q1 = df_treated[col].quantile(0.25)
  Q3 = df_treated[col].quantile(0.75)
  IQR=Q3-Q1
  lower = Q1 - 1.5 * IQR
  upper = Q3 + 1.5 * IQR

  df_treated[col] = df_treated[col].clip(lower, upper)
  print(f"{col}: values capped between {lower:.2f} and {upper:.2f}")

print("\nStatistics BEFORE treatment:")
print(df[numeric_cols].describe())

print("\nStatistics AFTER treatment:")
print(df_treated[numeric_cols].describe())

df_treated.to_csv("/content/student_performance_dataset (4).csv",index=False)
print("\nTreated dataset saved as '/content/student_performance_dataset (4).csv'")
print("Program executed Successfully")